// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Test} from "forge-std/Test.sol";
import {Volatility} from "../src/lib/Volatility.sol";

/// @notice Differential test between the deployed estimator and the Python model that
/// `analysis/stats.py` replays over historical flow.
///
/// The replay in the study is a REIMPLEMENTATION (`analysis/volatility_model.py`), not this
/// contract. Without this test, the study's headline numbers would be a property of a model
/// of the hook rather than of the hook. These expected values are generated by
/// `python3 analysis/volatility_model.py` and are asserted identically in
/// `analysis/test_differential.py`, so if either implementation drifts, one of the two fails.
///
/// UNITS: the contract measures `dt` in SECONDS; the replay measures it in BLOCKS, because the
/// dataset carries block numbers. Unichain produces one block per second, so they coincide
/// there. That substitution is disclosed wherever the replay's output is reported.
contract VolatilityDifferentialTest is Test {
    uint256 constant HALF_LIFE = 300;
    uint24 constant FEE_MIN = 500;
    uint24 constant FEE_MAX = 10_000;
    uint256 constant FEE_PER_SIGMA = 200;

    /// @dev Mirrors WindwardHook._feeFor so the fee column can be asserted too.
    function _fee(uint256 varianceWad) internal pure returns (uint256) {
        uint256 premium = (Volatility.sigmaWad(varianceWad) * FEE_PER_SIGMA) / Volatility.WAD;
        uint256 f = uint256(FEE_MIN) + premium;
        return f > FEE_MAX ? FEE_MAX : f;
    }

    /// @notice The fixed vector. Exercises a normal move, the `dt == 0` identity, a small move
    /// over a long gap (the case the old integer division truncated to zero), a quiet hour,
    /// a violent move, a day of silence, a tiny move, and the observation cap.
    function test_matchesPythonModelOnFixedVector() public pure {
        uint256 v = 0;

        // step 0: normal move, 10 ticks in 1s
        v = Volatility.update(v, 0, 10, 1, HALF_LIFE);
        assertEq(v, 166666666666666600, "step0 variance");
        assertEq(Volatility.sigmaWad(v), 408248290463862934, "step0 sigma");
        assertEq(_fee(v), 581, "step0 fee");

        // step 1: dt == 0 must be an identity (this is the W-01 fix)
        v = Volatility.update(v, 10, 10, 0, HALF_LIFE);
        assertEq(v, 166666666666666600, "step1 variance (dt==0 identity)");
        assertEq(_fee(v), 581, "step1 fee");

        // step 2: 2 ticks over 25s. Old code computed (2*2)/25 == 0 and lost it entirely.
        v = Volatility.update(v, 10, 12, 25, HALF_LIFE);
        assertEq(v, 166388888888888825, "step2 variance");
        assertEq(Volatility.sigmaWad(v), 407907941684013826, "step2 sigma");
        assertEq(_fee(v), 581, "step2 fee");

        // step 3: a quiet hour, decay only
        v = Volatility.update(v, 12, 12, 3600, HALF_LIFE);
        assertEq(v, 40622287326388, "step3 variance");
        assertEq(Volatility.sigmaWad(v), 6373561588812647, "step3 sigma");
        assertEq(_fee(v), 501, "step3 fee");

        // step 4: violent move -> ceiling
        v = Volatility.update(v, 12, 5000, 1, HALF_LIFE);
        assertEq(v, 41466906707221233594081, "step4 variance");
        assertEq(Volatility.sigmaWad(v), 203634247382951853003, "step4 sigma");
        assertEq(_fee(v), 10000, "step4 fee (ceiling)");

        // step 5: a day of silence releases the ceiling entirely (the W-02 fix)
        v = Volatility.update(v, 5000, 5000, 86400, HALF_LIFE);
        assertEq(v, 0, "step5 variance (decayed to zero)");
        assertEq(_fee(v), 500, "step5 fee (back to floor)");

        // step 6: a 1-tick move still registers (W-03: no truncation to zero)
        v = Volatility.update(v, 5000, 5001, 1, HALF_LIFE);
        assertEq(v, 1666666666666666, "step6 variance");
        assertEq(Volatility.sigmaWad(v), 40824829046386293, "step6 sigma");
        assertEq(_fee(v), 508, "step6 fee");

        // step 7: an enormous move binds the observation cap
        v = Volatility.update(v, 5001, -900000, 1, HALF_LIFE);
        assertEq(v, 166666668330555488888888, "step7 variance (capped)");
        assertEq(Volatility.sigmaWad(v), 408248292501702312862, "step7 sigma");
        assertEq(_fee(v), 10000, "step7 fee (ceiling)");
    }

    /// @notice decayFactor is the piece most likely to drift between the two languages.
    function test_decayFactorMatchesPythonModel() public pure {
        assertEq(Volatility.decayFactor(0, 300), 1000000000000000000, "dt=0");
        assertEq(Volatility.decayFactor(300, 300), 500000000000000000, "one half-life");
        assertEq(Volatility.decayFactor(600, 300), 250000000000000000, "two half-lives");
        assertEq(Volatility.decayFactor(150, 300), 750000000000000000, "half a half-life");
        assertEq(Volatility.decayFactor(25, 300), 958333333333333334, "25s");
        assertEq(Volatility.decayFactor(3600, 300), 244140625000000, "one hour");
        assertEq(Volatility.decayFactor(86400, 300), 0, "one day -> zero");
    }
}
